config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  get 'favorite/create'

  get 'favorite/destroy'

  get 'sessions/new'

  root to: 'tops#index'
  resources :favorites, only: [:create, :destroy]
  resources :tops
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :blogs do
   collection do
     post :confirm
     mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
   end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title,presence: true
  validates :content,length: { in: 1..140 }

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                    before_save { email.downcase! }
                    has_secure_password
                    validates :password, presence: true, length: { minimum: 6 }

  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_many :blogs
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
   before_action :set_blog, only: [:show, :edit, :update, :destroy]
   before_action :logged_in?, only: [:new, :edit, :show, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
     @blog = Blog.new(blog_params)
     @blog.image.retrieve_from_cache! params[:cache][:image]if params[:cache][:image].present?
    else
     @blog = Blog.new
    end

  end

  def edit
    # @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.image.retrieve_from_cache!  params[:cache][:image]if params[:cache][:image].present?
    if @blog.save
      BlogMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, notice: "写真を投稿しました！"
    else
      render 'new'
    end
  end


  def show
    @blog = Blog.find(params[:id])
    # @user = User.find_by(id: @blog.user_id)
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)

  end

  def update
   @blog = Blog.find(params[:id])
   if @blog.update(blog_params)
     redirect_to blogs_path, notice: "写真を編集しました！"
   else
     render 'edit'
   end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"写真を削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
     render :new if @blog.invalid?
  end



  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :user_id)
  end

  def set_blog
   @blog = Blog.find(params[:id])
  end

  def logged_in?
    if current_user.nil?
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to user_path(@user.id)

    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :名前 %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :年齢  %>
    <%= form.text_field :content %>
  </div>
  <br></br>
  <div class="field">
  <%= form.label :photo %>
  <%= form.file_field :image, id: :feed_image %>
  <%= form.hidden_field :image_cache %>
  </div>
  <br></br>

  <!-- <%= form.submit %> -->
  <button type="submit" class="btn btn-succes">Create Memory</button>
<% end %>
<br></br>

<%= link_to "BABY ALBUM", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="flash">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
</div>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>

  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ALBUM</h1>
<!-- <p><%= notice %></p> -->
<div class="content">
<div class="row">
  <% @blogs.each do |blog| %>
    <div class="col-md-3 col-xs-12">
      <table class="box">
        <div class="position">
          <tr class="test">
            <th></th>
          </tr>
          <tr>
            <th></th>
          </tr>
        </div>
        <tr>
          <td><%= blog.title %></td>
        </tr>
        <tr>
          <td><%= blog.content %></td>
        </tr>
        <tr>
          <td><%= image_tag blog.image %></td>
        </tr>
        <tr>
          <td><%= link_to '確認する', blog_path(blog.id) %></td>
        </tr>
        <% if logged_in? %>

          <% if blog.user_id == current_user.id %>
          <tr>
            <td><%= link_to "編集する", edit_blog_path(blog.id) %></td>
          </tr>
          <tr>
            <td><%= link_to '削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  <% end %>
</div>
</div>



<br>

<%= link_to '投稿する', new_blog_path %>

<!-- <div class="container">
<header class="header">Bootstrap</header>
<nav class="menu">
      <ul class="row">
          <li class="col-md-4">top</li>
          <li class="col-md-4">menu1</li>
          <li class="col-md-4">menu2</li>
      </ul>
</nav>
<article>
    <div class="contents">
        <ul>
            <li class="col-md-6">contents1</li>
            <li class="col-md-6">contents2</li>
        </ul>
    </div>
    <div class="topic">
         <ul>
            <li>bootstrapを使ってレスポンシブデザインを実現しよう！</li>
            <li>やればできる！bootstrapを使ってみよう！</li>
            <li>怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に！</li>
        </ul>
    </div>
</article>
</div> -->

app/views/blogs/new.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <h2>　  投稿する</h2>
      <br></br>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>例コード</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <link rel="stylesheet" type="text/css" href="/assets/slick/slick.css"/> -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"/>
<!-- <link rel="stylesheet" type="text/css" href="/assets/slick/slick-theme.css"/> -->

<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
  <meta name="viewport" content="width=device-width">
</head>
<body>
<div class="container">
  <header>
    <ul class="row">
      <!-- <li class="col-md-4"><a href="http://localhost:3000/tops">TOP PAGE</a></li> -->
      <li class="col-md-4"><%= link_to 'TOP PAGE', tops_path %>
      <li class="col-md-4"><%= link_to 'BABY ALBUM', blogs_path %>
      <li class="col-md-4"><%= link_to '投稿', new_blog_path %>
      <!-- <li class="col-md-4"><a href="http://localhost:3000/blogs#">BABY ALBUM</a></li> -->
      <!-- <li class="col-md-4"><a href="http://localhost:3000/blogs/new#">投稿</a></li> -->
    </ul>
  </header>
</div>
<div class="flash">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>

  <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id) %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Login", new_session_path %>
  <% end %>

<%= yield %>

  <footer>
    <p></p>
    <p>Thank you for coming into this world</p>
  </footer>


<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<!-- <script type="text/javascript" src="/assets/slick/slick.min.js"></script> -->
<script type="text/javascript">


$('.baby').slick({
  autoplay: true,
  autoplayspeed: 10000,
  slidesToShow: 1
});

</script>
</body>
</html>

app/views/tops/index.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-12 col-xs-12">


      <div class="baby">
        <div class><%= image_tag 'top.jpg' %></div>
        <div class><%= image_tag 'top7.jpg'%></div>
        <!-- <div class><%= image_tag 'top2.jpg'%></div> -->
        <div class><%= image_tag 'top3.jpg'%></div>
        <div class><%= image_tag 'top6.jpg'%></div>
        <div class><%= image_tag 'top8.jpg'%></div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>

  <div class="field">
  <%= f.label :photo %>
  <%= f.file_field :image, id: :feed_image %>
  <%= f.hidden_field :image_cache %>
  </div>
  
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<h1><%= image_tag @user.image %></h1>

<p>メールアドレス: <%= @user.email %></p>

<P>お気に入り一覧</P>

<% @favorite_blogs.each do |favorite_blog| %>
  <%= favorite_blog.title %>
  <%= favorite_blog.content %>
  <%= image_tag favorite_blog.image %>
<% end %>